#!/usr/bin/env python3
"""
Compute Lie brackets among cascade-internal generators at gauge layer d=12.

CLAIM TO TEST.  The cascade's d=12 layer has:
  - 3 Adams nowhere-vanishing vector fields on S^11 (rho(12)-1 = 3).
  - The cascade's complex structure J on R^12 = C^6.
The audit suggested these (plus brackets) might supply enough Lie-algebra
content to close as su(3).  This script computes the brackets explicitly
and tests whether the closure is su(3) or something smaller.

SETUP.

R^12 = H^3 (3 quaternions).  Each H = R^4 with basis (1, i, j, k).

Adams vector fields at d=12: right-multiplication by quaternion i, j, k on
H^3.  These are the canonical 3 nowhere-vanishing tangent fields on S^11.
(Other choices exist by Sp(3) rotation but are equivalent up to isomorphism.)

V_R^i, V_R^j, V_R^k: block-diagonal 12x12 skew-symmetric matrices.

Cascade J at d=12: complex structure on R^12 = C^6.  Two natural choices:
  (a) Left-multiplication by quaternion i (block-diagonal 4x4).
  (b) Pair-wise complex structure on C^6 = R^12 (different blocking).
Both give J^2 = -I and skew-symmetric.  We test (a) (the quaternion-
natural one).

EXPECTED RESULT.  Quaternionic left and right multiplications COMMUTE
(standard fact).  So J commutes with V_R^i, V_R^j, V_R^k.  The Lie sub-
algebra generated by {J, V_R^i, V_R^j, V_R^k} is u(1) x su(2) = u(2),
dim 4.

This is NOT su(3) (dim 8).  Cascade's 3 Adams + J gives u(2), missing 4
generators of su(3).

TEST.  Compute brackets and verify dimensional closure.
"""
import numpy as np


def quat_right_mult_i():
    """Right-mult by quaternion i: (a,b,c,d) -> (-b, a, d, -c) on H = R^4."""
    return np.array([
        [0, -1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, -1, 0]
    ], dtype=float)


def quat_right_mult_j():
    """Right-mult by quaternion j: (a,b,c,d) -> (-c, -d, a, b)."""
    return np.array([
        [0, 0, -1, 0],
        [0, 0, 0, -1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]
    ], dtype=float)


def quat_right_mult_k():
    """Right-mult by quaternion k: (a,b,c,d) -> (-d, c, -b, a)."""
    return np.array([
        [0, 0, 0, -1],
        [0, 0, 1, 0],
        [0, -1, 0, 0],
        [1, 0, 0, 0]
    ], dtype=float)


def quat_left_mult_i():
    """Left-mult by quaternion i: (a,b,c,d) -> (-b, a, -d, c)."""
    return np.array([
        [0, -1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, -1],
        [0, 0, 1, 0]
    ], dtype=float)


def block_diag_n(M, n):
    """Block-diagonal n copies of M."""
    rows, cols = M.shape
    out = np.zeros((n * rows, n * cols))
    for i in range(n):
        out[i*rows:(i+1)*rows, i*cols:(i+1)*cols] = M
    return out


def bracket(A, B):
    return A @ B - B @ A


def is_in_span(M, basis_list, tol=1e-9):
    """Check if matrix M is in the linear span of basis_list (matrices)."""
    if not basis_list:
        return np.allclose(M, 0, atol=tol), None
    M_vec = M.flatten()
    B_vecs = np.array([b.flatten() for b in basis_list]).T
    coeffs, residuals, rank, _ = np.linalg.lstsq(B_vecs, M_vec, rcond=None)
    reconstructed = B_vecs @ coeffs
    in_span = np.allclose(reconstructed, M_vec, atol=tol)
    return in_span, coeffs


def lie_algebra_closure(generators, max_dim=200, tol=1e-9):
    """Compute the Lie algebra generated by a set of matrices.

    Returns: list of basis elements (matrices), dimension.
    """
    basis = []
    queue = list(generators)
    iteration = 0
    while queue and len(basis) < max_dim:
        iteration += 1
        if iteration > 1000:
            print(f"WARNING: max iterations reached at {len(basis)} basis elements")
            break

        M = queue.pop(0)
        # Check if M is in current span
        in_span, _ = is_in_span(M, basis, tol)
        if in_span:
            continue
        # Add to basis
        basis.append(M)
        # Add all brackets [M, b] for b in basis
        for b in basis:
            queue.append(bracket(M, b))
            queue.append(bracket(b, M))
    return basis, len(basis)


def main():
    print("=" * 78)
    print("CASCADE LIE BRACKET COMPUTATION AT d=12")
    print("=" * 78)
    print()
    print("Setup: R^12 = H^3 (three quaternions).")
    print("Adams fields at d=12: right-mult by quaternion i, j, k on H^3.")
    print("Cascade J: left-mult by quaternion i on H^3.")
    print()

    # Construct generators
    Vi_local = quat_right_mult_i()
    Vj_local = quat_right_mult_j()
    Vk_local = quat_right_mult_k()
    Ji_local = quat_left_mult_i()

    # Verify local quaternion algebra
    print("=" * 78)
    print("Step 1: Verify local quaternion algebra on H = R^4")
    print("=" * 78)
    print()

    # Check skew-symmetry
    for name, M in [("V_R^i", Vi_local), ("V_R^j", Vj_local),
                     ("V_R^k", Vk_local), ("J_L^i", Ji_local)]:
        is_skew = np.allclose(M + M.T, 0)
        print(f"  {name} skew-symmetric: {is_skew}")

    # Check J^2 = -I
    print(f"  J_L^i^2 = -I: {np.allclose(Ji_local @ Ji_local, -np.eye(4))}")

    # Check quaternion algebra: ij = k, jk = i, ki = j (right-mult composition)
    # Right-mult by i then j: x*i*j = x*(ij) = x*k -> matrix product Vj * Vi
    print()
    print("  Quaternion algebra (right-mult compositions):")
    Vij = Vj_local @ Vi_local
    print(f"    V_R^j @ V_R^i (= right-mult by ij = k): equals V_R^k? "
          f"{np.allclose(Vij, Vk_local)}")
    Vjk = Vk_local @ Vj_local
    print(f"    V_R^k @ V_R^j (= right-mult by jk = i): equals V_R^i? "
          f"{np.allclose(Vjk, Vi_local)}")
    Vki = Vi_local @ Vk_local
    print(f"    V_R^i @ V_R^k (= right-mult by ki = j): equals V_R^j? "
          f"{np.allclose(Vki, Vj_local)}")
    print()

    # Brackets among right-mults: should give 2x the quaternion product
    # [V_R^i, V_R^j] = V_R^i V_R^j - V_R^j V_R^i
    # V_R^i V_R^j = right-mult by ji = -k, so V_R^i V_R^j = -V_R^k
    # V_R^j V_R^i = right-mult by ij = k, so V_R^j V_R^i = V_R^k
    # So [V_R^i, V_R^j] = -V_R^k - V_R^k = -2 V_R^k
    print("  Brackets [V_R^i, V_R^j]:")
    bij = bracket(Vi_local, Vj_local)
    print(f"    [V_R^i, V_R^j] = -2 V_R^k? {np.allclose(bij, -2 * Vk_local)}")
    bjk = bracket(Vj_local, Vk_local)
    print(f"    [V_R^j, V_R^k] = -2 V_R^i? {np.allclose(bjk, -2 * Vi_local)}")
    bki = bracket(Vk_local, Vi_local)
    print(f"    [V_R^k, V_R^i] = -2 V_R^j? {np.allclose(bki, -2 * Vj_local)}")
    print()
    print("  Note: brackets close as su(2) (3-dim non-Abelian Lie algebra).")
    print()

    # Now check J vs V brackets
    print("=" * 78)
    print("Step 2: J commutes with right-mult fields (left-right commutativity)")
    print("=" * 78)
    print()

    for name, V in [("V_R^i", Vi_local), ("V_R^j", Vj_local), ("V_R^k", Vk_local)]:
        commutator = bracket(Ji_local, V)
        commutes = np.allclose(commutator, 0)
        print(f"  [J_L^i, {name}] = 0? {commutes}")
    print()
    print("  Quaternionic left and right multiplications COMMUTE.")
    print("  This is a standard fact (the algebra of right multiplications")
    print("  commutes with the algebra of left multiplications).")
    print()

    # Build full 12x12 generators
    Vi = block_diag_n(Vi_local, 3)
    Vj = block_diag_n(Vj_local, 3)
    Vk = block_diag_n(Vk_local, 3)
    J = block_diag_n(Ji_local, 3)

    # Compute Lie algebra generated by {Vi, Vj, Vk, J}
    print("=" * 78)
    print("Step 3: Lie algebra generated by {V_R^i, V_R^j, V_R^k, J_L^i} on R^12")
    print("=" * 78)
    print()

    basis, dim = lie_algebra_closure([Vi, Vj, Vk, J])
    print(f"  Generated Lie algebra dimension: {dim}")
    print()

    # Identify the algebra
    if dim == 4:
        print("  4-dim Lie algebra.  Structure: u(1) x su(2) = u(2)")
        print("  - 1 Abelian generator (J)")
        print("  - 3 su(2) generators (V_R^i, V_R^j, V_R^k)")
        print("  - J commutes with all V's (verified above)")
    elif dim == 8:
        print("  8-dim Lie algebra.  Could be su(3)!  Need to verify structure.")
    else:
        print(f"  {dim}-dim Lie algebra.  Doesn't match standard SU(N) sizes.")
    print()

    # Compare with su(3) requirement
    print("=" * 78)
    print("Step 4: comparison with su(3) requirement")
    print("=" * 78)
    print()
    print(f"  Cascade's d=12 algebra (Adams + J): dim {dim}")
    print(f"  Required for SU(3): dim 8")
    print(f"  Gap: {8 - dim} generators missing")
    print()

    if dim == 4:
        print("  CONFIRMED: cascade-internal structure at d=12 generates u(2),")
        print("  not su(3).  The 4 missing generators (off-diagonal Gell-Mann")
        print("  matrices that mix the 3 H factors) are NOT supplied by Adams +")
        print("  cascade J.")
        print()
        print("  Where could they come from?")
        print("  - Permutations of the 3 H factors: 3-dim symmetric group action.")
        print("    But these aren't 'cascade-internal' in any forced sense -- they")
        print("    require choosing a labelling of the 3 quaternions.")
        print("  - SO(12) Killing fields at large: cascade has access to all 66")
        print("    so(12) generators.  Selecting an su(3) embedding requires")
        print("    additional structure beyond Adams + J.")
        print("  - Cross-quaternion automorphisms (e.g., from G_2 acting on")
        print("    octonions): but octonions are at d=8, not d=12.")
        print()
        print("  None of these provides a CASCADE-FORCED su(3).")

    # === Step 5: numerical bracket structure (verify su(2) for Adams subset)
    print("=" * 78)
    print("Step 5: verify su(2) structure of Adams subset {V_R^i, V_R^j, V_R^k}")
    print("=" * 78)
    print()

    # Check all brackets close in the 3-dim span
    bracket_check = True
    for n1, V1 in [("Vi", Vi), ("Vj", Vj), ("Vk", Vk)]:
        for n2, V2 in [("Vi", Vi), ("Vj", Vj), ("Vk", Vk)]:
            br = bracket(V1, V2)
            in_span_v, _ = is_in_span(br, [Vi, Vj, Vk], tol=1e-9)
            if not in_span_v:
                bracket_check = False
                print(f"  [{n1}, {n2}] NOT in span of Adams!")

    if bracket_check:
        print("  All brackets [V_a, V_b] for a,b in {i,j,k} stay in span(Vi,Vj,Vk).")
        print("  Confirmed: 3 Adams fields generate a 3-dim su(2) sub-algebra.")
    print()

    # === Step 6: structural conclusion
    print("=" * 78)
    print("Step 6: structural conclusion for d=12")
    print("=" * 78)
    print()
    print(f"Cascade-internal Lie algebra at d=12 (Adams + cascade J): u(2), dim 4.")
    print(f"SU(3) gauge group requires: su(3), dim 8.")
    print(f"Gap: 4 generators missing.")
    print()
    print("VERDICT: The audit's IGN items (8.3 SO(d) Killing fields, 8.4")
    print("Equivariant index) do supply additional generators in PRINCIPLE")
    print("(so(12) has 66 generators, plenty of su(3) embeddings exist), but")
    print("none of them is cascade-forced from Adams + cascade J alone.")
    print()
    print("To upgrade cascade-internal structure from u(2) to su(3) at d=12,")
    print("an additional cascade-internal mechanism is needed that picks out")
    print("a specific su(3) ⊂ so(12) embedding.  No such mechanism has been")
    print("identified.")
    print()
    print("This refines the earlier 'no candidate identified' verdict: the")
    print("audit pointed to correct ingredients (so(12), Killing fields), but")
    print("the SELECTION of su(3) within so(12) requires structure the cascade")
    print("doesn't supply.")


if __name__ == "__main__":
    main()
