#!/usr/bin/env python3
"""
U2 FROM FIRST PRINCIPLES: the rule-set generated by the foundation,
not stipulated.

WHAT CHANGES vs cascade_u2_function.py (v1): v1 stipulates ten
clauses.  Here the same function is RECONSTRUCTED from the arithmetic
foundation (T1-T9), and three whole stipulations DISAPPEAR as
separate rules:
  - the P>L>G precedence order   -> frame NESTING (below)
  - the Family-B null clause R10 -> emergent (no frame -> no member)
  - the k-table (1/3/2*periods)  -> frame CONTACT COUNTING
and the point-vs-window gauge reading becomes a THEOREM of the T5
increment rule instead of a sharpened predicate.

THE FOUNDATION-SIDE DERIVATIONS, clause by clause:

  Obstruction rank = WINDING NUMBER of the Weil-index clock.  The
    Weil index gamma = zeta_8 has order 8 (the arithmetic Bott
    clock, gamma^4 = -1 the torsion flip).  A twist shift of 8
    returns the same local constant, so crossing legs g1 -> g2
    winds the clock |dg|/8 full cycles; each complete cycle is one
    obstruction factor.  DERIVED (order of the Weil index).

  Colour rank = [Q(zeta_3):Q] = 2.  Colour characters live in
    Q(zeta_3); fixing the colour frame is one field-degree's worth
    of Cartan data = 2.  T9 (one record, one frame) fixes the frame
    ONCE per record, so the rank is 2 for ANY quark content, not
    2-per-quark-leg -- the reading the uniqueness exhaustion found
    data-forced (killed alternatives died on m_b/m_tau).  DERIVED
    (field degree) + T9 identification (once-per-record).

  Projection rank = one trace-duality frame change (T8): crossing
    from a Z[omega]-valued leg to a Z-valued leg passes through the
    inverse different once.  DERIVED (T8).

  Gauge mediation = BAND FACTOR IN THE INCREMENT SUPPORT.  By the
    T5 increment rule, a window Phi(a,b) is the product of the
    increments Gamma_R(t+1)/Gamma_R(t) for t in the HALF-OPEN set
    (a,b] -- the increment attaches to its upper endpoint.  So a
    window is gauge-mediated iff its support (a,b] meets the gauge
    band {12,13,14}; a POINT value has empty support (it is a
    single local norm, not a transport) and can never mediate.
    This DERIVES, rather than stipulates: (i) why points do not
    count (v1's post-hoc sharpening, killed-by-theta_C in the
    exhaustion, is a theorem here); (ii) why mu/e's window (14,21)
    fails -- support {15..21} misses the band; (iii) why alpha_s's
    (5,12) succeeds -- support {6..12} contains 12.  DERIVED (T5).

  FRAME NESTING replaces the precedence order.  T9: one record, one
    frame.  The frames available to a record nest by logical
    priority -- a unit anchor must be resolved before any frame
    question (a dimensionful number is meaningless unanchored); the
    observer frame before mediation (locality is a property of the
    read, mediation of the path); the bilinear frame is innermost
    (the overlap's own two legs).  Resolution takes the OUTERMOST
    available frame:
        unit  >  observer  >  gauge  >  bilinear  >  (none)
    This yields exactly P>L>G and, for free, the Amplitude default.
    STATUS: PARTIAL -- the nesting is an argument (logical priority
    of unit-fixing over frame-fixing over path-dressing), not a
    theorem; but it is the same argument at every level, where the
    v1 precedence was an unexplained order.  It selects PLG among
    the exhaustion's three surviving orders.

  k = CONTACT COUNT of the resolved frame:
      unit frame     : 1  (one absolute anchor, the ln Gamma(1/2)
                           threshold)
      observer frame : |{5,13,21}| = 3  (the observer's read closes
                           once per T6-marked coset -- the marked
                           set's size is a THEOREM, T6; the
                           identification read-closes-per-coset is
                           the remaining step).  NOTE: this is NOT
                           "three spatial dimensions" -- that
                           framing is barred (Check 8) and
                           unnecessary.
      gauge frame    : 1  (one band, one frame)
      bilinear frame : 2 x (periods touched by full content) -- a
                           bilinear form contacts each touched
                           period through BOTH legs.
    The v1 k-table becomes one counting principle.  STATUS: PARTIAL
    (the per-frame contact identifications are argued, with the
    Observer 3 upgraded from soft input to |marked set| via T6).

  MEMBER EXISTENCE is emergent: a member is a chi-attachment to the
    resolved frame, so no frame -> no member (Family B, the
    radiative slot).  v1's R10 clause is not needed.  DERIVED
    (given the nesting).

  Population class + sign: a density is a measure (Geometric); an
    overlap is a bilinear form (Amplitude); all else descends
    (Descent).  Sign by T7 (Bohr-Mollerup), a theorem.  DERIVED.

STILL INHERITED / OPEN (stated, not hidden): the source VALUES for
the gauge and bilinear frames (14 = the band's top twist, 7 = the
amplitude twist) are read from the address structure, not re-derived
here (19 = ln Gamma(1/2) threshold and 5 = observer twist are
foundation objects); the kind classifications ride on D1; the A13
novel-vs-inherited grading remains an input.

THE TESTS: (1) the reconstructed function must reproduce all 11
stored rows with NO precedence order, NO null clause, and NO k-table
in the code; (2) it must adjudicate each of the exhaustion's five
probe forks -- first principles picks a branch where data could not.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cascade_u2_function import CASES, EXPECT, periods_touched
from cascade_u2_uniqueness import PROBES

CLOCK = 8              # order of the Weil index gamma = zeta_8
DEG_COLOUR_FIELD = 2   # [Q(zeta_3):Q]
MARKED = (5, 13, 21)   # T6: the forced marked set
BAND = {12, 13, 14}    # gauge twists (Radon-Hurwitz multiplicities)
THRESHOLD = 19         # ln Gamma(1/2) crossing (foundation object)
OBSERVER = 5           # observer twist (foundation object)
BAND_TOP = 14          # inherited from the address structure
AMPLITUDE_TWIST = 7    # inherited from the address structure


def support(win):
    """Increment support of Phi(a,b): the half-open twist set (a,b].

    T5: Phi(a,b) = sum of log[Gamma_R(t+1)/Gamma_R(t)], t = a+1..b;
    each increment attaches to its upper endpoint.  A point value is
    not a transport: empty support."""
    if not isinstance(win, tuple) or win[0] >= win[1]:
        return set()
    a, b = win
    return set(range(a + 1, b + 1))


def u2_first_principles(row):
    name, legs, novel, full, kind, dim = row
    gens = [g for g, k in legs if k in ("quark", "lepton")]

    # availability: winding number, field degree, duality change
    obstr = abs(gens[0] - gens[1]) // CLOCK if len(gens) == 2 else 0
    colour = DEG_COLOUR_FIELD if any(k == "quark" for _, k in legs) else 0
    proj = 1 if {"quark", "lepton"} <= {k for _, k in legs} else 0

    # population class and T7 sign
    pop = ("Geometric" if kind == "density" else
           "Amplitude" if kind == "overlap" else "Descent")
    sign = "+" if pop == "Descent" else "-"

    # frame nesting (T9: one record, one frame) -- outermost wins;
    # k = contact count of the resolved frame; no frame -> no member
    if dim:
        frame = ("Absolute", THRESHOLD, 1)
    elif kind in ("local-ratio", "density"):
        frame = ("Observer", OBSERVER, len(MARKED))
    elif support(novel) & BAND:
        frame = ("Gauge", BAND_TOP, 1)
    elif kind == "overlap":
        frame = ("Amplitude", AMPLITUDE_TWIST, 2 * periods_touched(full))
    else:
        frame = None
    member = None if frame is None else (pop, frame[1], frame[2], sign)
    return dict(avail=(obstr, colour, proj), member=member)


def main():
    print("=" * 74)
    print("U2 FROM FIRST PRINCIPLES: reconstruction vs stored table")
    print("=" * 74)
    print("  (no precedence order, no null clause, no k-table in the code)")
    print()
    npass = nfail = 0
    for row in CASES:
        got = u2_first_principles(row)
        exp = EXPECT[row[0]]
        bad = [(key, got[key], exp[key]) for key in exp if got[key] != exp[key]]
        status = "PASS" if not bad else "FAIL"
        npass += not bad
        nfail += bool(bad)
        print(f"  {status}  {row[0]:<11} avail={got['avail']}"
              f" member={got['member']}")
        for key, g, e in bad:
            print(f"         ** {key}: derived {g} != stored {e}")
    print()
    print(f"  RESULT: {npass}/{npass + nfail} rows from the foundation-side"
          f" reconstruction")
    print()
    print("=" * 74)
    print("FORK ADJUDICATION (the exhaustion's five probes, now decided)")
    print("=" * 74)
    for probe in PROBES:
        got = u2_first_principles(probe)
        print(f"  {probe[0]}:")
        print(f"    first principles -> avail={got['avail']}"
              f" member={got['member']}")
    print()
    print("  Each probe lands on the CANONICAL branch of its exhaustion")
    print("  fork: P1 winding=2 (Weil clock, vs the indicator variant);")
    print("  P2 gauge-mediated (support {14..20} meets the band -- the")
    print("  lo<12 variant is arithmetically wrong); P3 Observer and P4")
    print("  Absolute (nesting -> PLG uniquely, from the exhaustion's")
    print("  three surviving orders); P5 no frame -> None (the kind-")
    print("  restricted null variant is excluded).  The forks remain")
    print("  registered predictions -- but now with derived values, so a")
    print("  future row disagreeing falsifies the FOUNDATION account,")
    print("  not merely a clause choice.")
    print()
    print("=" * 74)
    print("DERIVATION LEDGER")
    print("=" * 74)
    print("  DERIVED : obstruction (Weil-index order 8); colour rank")
    print("            ([Q(zeta_3):Q]=2); projection (T8, one duality")
    print("            change); gauge support reading (T5 increment rule");
    print("            -- v1's post-hoc sharpening is a theorem here);")
    print("            member existence (emergent from frames); class +")
    print("            sign (T7).")
    print("  PARTIAL : frame nesting (priority argument, selects PLG);")
    print("            contact counts (Observer 3 = |{5,13,21}| via T6 --")
    print("            soft input upgraded to marked-set size, one")
    print("            identification step left; bilinear 2 = two legs;")
    print("            NOT 'three spatial dimensions' -- Check 8).")
    print("  INHERITED: source twists 14 (band top) and 7 (amplitude);")
    print("            kind classifications ride on D1; A13 grading.")


if __name__ == "__main__":
    main()
