#!/usr/bin/env python3
"""
Composites of the cascade's two complex structures.

Addendum 3 found: J-twists on the layer chain are gauge-trivial (path graph,
no loops), and the pairing-offset ambiguity gives two complex structures
J1, J2 whose composite T = J2 J1 is a signed two-step SHIFT along the axis
chain.  This script investigates the composites systematically.

  A. Algebra: what Lie algebra do J1 and J2 generate under commutators?
     (full so(n)?  a proper subalgebra?)
  B. Phase-triviality theorem, checked: any operator whose hop phases are a
     function of DISPLACEMENT only (the cascade's i-per-step rule, phase
     i^(Delta d)) is gauge-equivalent to a real operator via U = diag(i^d);
     no composite of displacement-phased hops can ever carry flux.
  C. The loophole: T's signs are PARITY-dependent (evens shift up with +,
     odds shift down with +), i.e. position- not displacement-dependent.
     Combining the elastic chain (1-step, real) with the skew composite
     i(T - T^t) (2-step) closes triangles.  Measure the actual flux through
     every triangle; if nonzero, this is the first genuinely un-gaugeable
     cascade-native operator, and its level statistics get the same
     GUE/GOE/Poisson/crystal test as before.

Pre-registered priors: (A) full so(n); (B) triviality confirmed exactly;
(C) some nonzero staggered flux is possible, but the spectrum of a
deterministic quasi-1-D operator stays regular -- not GUE (0.5996).
"""

import math
from itertools import combinations

import numpy as np

D_MIN, D_MAX = 4, 217


def lnR(d):
    return math.lgamma((d + 1) / 2.0) - math.lgamma((d + 2) / 2.0)


def alpha(d):
    return math.exp(2.0 * lnR(d)) / 4.0


def N_lapse(d):
    return math.sqrt(math.pi) * math.exp(lnR(d))


def gap_ratio(e):
    s = np.diff(np.sort(e))
    s = s[s > 1e-12]
    r = np.minimum(s[1:], s[:-1]) / np.maximum(s[1:], s[:-1])
    return float(np.mean(r))


def spacing_cv(e):
    s = np.diff(np.sort(e))
    s = s[s > 1e-12]
    k = 9
    loc = np.array([np.mean(s[max(0, i - k // 2):i + k // 2 + 1])
                    for i in range(len(s))])
    u = s / loc
    return float(np.std(u) / np.mean(u))


def pairing_J(n, offset):
    J = np.zeros((n, n))
    k = offset
    while k + 1 < n:
        J[k + 1, k] = 1.0
        J[k, k + 1] = -1.0
        k += 2
    return J


# ---------------------------------------------------------------------------
def part_A():
    print("=" * 78)
    print("PART A: Lie algebra generated by J1, J2")
    print("=" * 78)
    for n in (6, 8, 10, 12):
        J1, J2 = pairing_J(n, 0), pairing_J(n, 1)
        basis = [J1, J2]
        rank = 2
        while True:
            new = []
            for A, B in combinations(basis, 2):
                new.append(A @ B - B @ A)
            cand = basis + new
            M = np.array([c.flatten() for c in cand])
            r = np.linalg.matrix_rank(M, tol=1e-9)
            if r == rank:
                break
            # keep an independent subset
            q, rr, piv = np.linalg.qr(M.T, mode='reduced'), None, None
            u, s, vt = np.linalg.svd(M, full_matrices=False)
            keep = [cand[i] for i in range(len(cand))]
            basis, rank = keep, r
            if len(basis) > 4 * n * n:
                break
        dim_so = n * (n - 1) // 2
        m = n // 2
        tag = ("= (n/2)^2 = dim u(n/2)" if rank == m * m else
               ("FULL so(n)" if rank == dim_so else "proper subalgebra"))
        print(f"  n = {n:2d}: closure dim = {rank:3d}   dim so(n) = {dim_so:3d}"
              f"   {tag}")
    # identify the algebra for n = 12: center of the closure
    n = 12
    J1, J2 = pairing_J(n, 0), pairing_J(n, 1)
    basis = [J1, J2]
    for _ in range(6):
        new = [A @ B - B @ A for A, B in combinations(basis, 2)]
        M = np.array([c.flatten() for c in basis + new])
        u, s, vt = np.linalg.svd(M, full_matrices=False)
        r = int((s > 1e-9 * s[0]).sum())
        basis = [vt[i].reshape(n, n) for i in range(r)]
        if len(basis) == r and r == (n // 2) ** 2:
            break
    # ideal decomposition via the adjoint Casimir: orthonormalise basis
    # under tr(A^T B), build structure constants, C = sum_i (ad B_i)^2;
    # by Schur C is a constant on each simple ideal -> eigenvalue
    # multiplicities = ideal dimensions.
    G = np.array([b.flatten() for b in basis])
    u3, s3, vt3 = np.linalg.svd(G, full_matrices=False)
    ob = [vt3[i].reshape(n, n) for i in range(len(basis))]
    r = len(ob)
    ad = np.zeros((r, r, r))
    Pn = np.array([b.flatten() for b in ob]).T
    for i in range(r):
        for j in range(r):
            br = (ob[i] @ ob[j] - ob[j] @ ob[i]).flatten()
            ad[i][:, j] = 0.0
            coeff, *_ = np.linalg.lstsq(Pn, br, rcond=None)
            ad[i][:, j] = coeff
    C = sum(ad[i] @ ad[i] for i in range(r))
    ev = np.sort(np.linalg.eigvalsh(C))
    groups = []
    for v in ev:
        if groups and abs(v - groups[-1][0]) < 1e-6 * max(1, abs(v)):
            groups[-1][1] += 1
            groups[-1][0] = v
        else:
            groups.append([v, 1])
    mult = sorted(g[1] for g in groups)
    cdim = sum(g[1] for g in groups if abs(g[0]) < 1e-8)
    print(f"  adjoint-Casimir block dimensions: {mult}"
          f"   (eigenvalues {[round(float(g[0]), 4) for g in groups]})")
    print(f"  center dim (Casimir kernel) = {cdim}   (u(m) predicts 1)")
    # the 1-dim block: reconstruct its element Z and test centrality
    w_ev, V = np.linalg.eigh(C)
    order = np.argsort(w_ev)
    # find index of the isolated eigenvalue
    iso = None
    for g in groups:
        if g[1] == 1:
            iso = g[0]
    idx = int(np.argmin(np.abs(w_ev - iso)))
    zc = V[:, idx]
    Z = sum(zc[i] * ob[i] for i in range(r))
    Z = Z / math.sqrt(abs(np.trace(Z @ Z)) / n)
    comm = max(np.linalg.norm(Z @ B - B @ Z) for B in ob)
    err = np.linalg.norm(Z @ Z + np.eye(n))
    print(f"  isolated block's element Z:  max ||[Z, basis]|| = {comm:.2e},"
          f"  ||Z^2 + I|| = {err:.2e}")
    if comm < 1e-6 and err < 1e-6:
        print("  => VERIFIED: the closure is u(n/2) = span(Z) + su(n/2), with")
        print("     Z an EMERGENT complex structure (Z^2 = -I) that commutes")
        print("     with everything the two pairings generate.  The pairing")
        print("     ambiguity is self-repairing: J1, J2 disagree about which")
        print("     axes are partners, but their composites close on the")
        print("     unitary algebra of a single canonical J.")
    else:
        print("  => 1-dim block is NOT central: algebra is semisimple of dim")
        print("     (n/2)^2 with the block structure printed above.")


# ---------------------------------------------------------------------------
def part_B():
    print()
    print("=" * 78)
    print("PART B: displacement-phase triviality (the i-per-step rule)")
    print("=" * 78)
    d = np.arange(D_MIN, D_MAX + 1)
    n = len(d)
    w1 = np.array([1.0 / (2.0 * alpha(int(x))) for x in d[:-1]])
    w2 = np.array([N_lapse(int(x)) * N_lapse(int(x) + 1) for x in d[:-2]])
    H = np.zeros((n, n), dtype=complex)
    for j, w in enumerate(w1):                      # 1-step hops, phase i
        H[j + 1, j] = -w * 1j
        H[j, j + 1] = np.conj(H[j + 1, j])
        H[j, j] += w
        H[j + 1, j + 1] += w
    for j, w in enumerate(w2):                      # 2-step hops, phase i^2
        H[j + 2, j] = -w * (1j ** 2)
        H[j, j + 2] = np.conj(H[j + 2, j])
    U = np.diag([1j ** k for k in range(n)])
    Hg = U.conj().T @ H @ U
    print(f"  max |Im| of gauge-transformed operator: "
          f"{np.max(np.abs(Hg.imag)):.2e}")
    e1 = np.linalg.eigvalsh(H)
    e2 = np.linalg.eigvalsh(Hg.real)
    print(f"  max eigenvalue difference vs real form: "
          f"{np.max(np.abs(e1 - e2)):.2e}")
    print("  => i^(Delta d) phases are pure gauge on ANY graph: no composite")
    print("     of displacement-phased cascade hops can carry flux.  The")
    print("     cascade's imaginary unit has zero curvature.")


# ---------------------------------------------------------------------------
def part_C():
    print()
    print("=" * 78)
    print("PART C: chain + skew shift composite i(T - T^t)  (parity signs)")
    print("=" * 78)
    d = np.arange(D_MIN, D_MAX + 1)
    n = len(d)
    # T = J2 J1 restricted to the layer index chain
    J1, J2 = pairing_J(n, 0), pairing_J(n, 1)
    T = J2 @ J1
    w1 = np.array([1.0 / (2.0 * alpha(int(x))) for x in d[:-1]])
    w2 = np.array([N_lapse(int(x)) * N_lapse(int(x) + 1) for x in d[:-2]])
    H = np.zeros((n, n), dtype=complex)
    for j, w in enumerate(w1):
        H[j, j] += w
        H[j + 1, j + 1] += w
        H[j, j + 1] = -w
        H[j + 1, j] = -w
    S = (T - T.T) / 2.0
    for j in range(n - 2):
        c = 1j * w2[j] * S[j + 2, j]
        if abs(c) > 0:
            H[j + 2, j] += c
            H[j, j + 2] += np.conj(c)
    assert np.allclose(H, H.conj().T)
    # flux through every triangle (j, j+1, j+2)
    fluxes = []
    for j in range(n - 2):
        h1, h2, h3 = H[j + 1, j], H[j + 2, j + 1], H[j, j + 2]
        if abs(h1) > 0 and abs(h2) > 0 and abs(h3) > 0:
            fluxes.append(np.angle(h1 * h2 * h3))
    fluxes = np.array(fluxes)
    nz = np.abs(np.abs(fluxes) - math.pi / 2) < 1e-9
    print(f"  triangles: {len(fluxes)};  flux = +-pi/2 on {nz.sum()} of them"
          f"  (unique |flux| values: "
          f"{sorted(set(np.round(np.abs(fluxes)/math.pi, 3)))} pi)")
    # is it gauge-removable?  try the parity gauge U = diag(i^(d(d-1)/2))-ish:
    # generic test: real-equivalence iff there is a diagonal unitary making H
    # real; equivalently all cycle phases are 0 or pi.  Report directly:
    frustrated = np.abs(np.mod(np.abs(fluxes), math.pi)) > 1e-9
    print(f"  un-gaugeable (flux not in {{0, pi}}): {frustrated.sum()} triangles"
          f"  -> time-reversal genuinely {'BROKEN' if frustrated.any() else 'intact'}")
    e = np.linalg.eigvalsh(H)
    print(f"  spectrum: {n} levels;  <r~> = {gap_ratio(e):.4f}"
          f"   CV(unfolded) = {spacing_cv(e):.4f}")
    lo, hi = np.percentile(e, [10, 90])
    bulk = e[(e > lo) & (e < hi)]
    print(f"  bulk (10-90 pct): <r~> = {gap_ratio(bulk):.4f}"
          f"   CV = {spacing_cv(bulk):.4f}")
    print("  reference: Poisson 0.3863 | GOE 0.5307 | GUE 0.5996 | crystal ~1")
    return e


if __name__ == "__main__":
    part_A()
    part_B()
    e = part_C()
    print()
    r = gap_ratio(e)
    print("VERDICT")
    if r > 0.75:
        print("  crystalline: composites do not break the rigidity")
    elif abs(r - 0.5996) < 0.02:
        print("  GUE-compatible (!!): immediate follow-up required")
    elif abs(r - 0.5307) < 0.02:
        print("  GOE-like: repulsion without broken time reversal")
    elif abs(r - 0.3863) < 0.03:
        print("  Poisson-like: integrable, uncorrelated levels")
    else:
        print("  intermediate/regular: none of the RMT classes")
