#!/usr/bin/env python3
"""
(R1b) attack via representation theory: derive the sector-fundamental
U(1)_Y rule from path-tensor Hilbert space normalization.

CONTEXT
=======
PR #115 ruled out Gram structure as the (R1b) closure mechanism.  The
correct angle is REPRESENTATION-THEORETIC: derive
  Y_smallest_for_(V_12, V_13)_sector = 1 / (dim V_12 * dim V_13)
from cascade primitives (Adams + path-tensor + J at d=14).

THE PUZZLE
==========
Cascade U(1)_Y at d=14 is generated by J on R^14 = C^7.  J has
eigenvalues +/- i, so charges in cascade-native units are integer
+/- 1.  Standard rep theory: U(1) is compact, smallest non-trivial
charge = 1.

But SM matter has FRACTIONAL Y values: 1/6, 1/3, 1/2, 1.  How does
the cascade give fractional Y from a J with integer eigenvalues?

POSSIBLE RESOLUTIONS
====================
(R1) Cascade U(1)_Y generator is J/(N_c * N_doublet) for matter in
     (3, 2) sector, J/N_c for (3, 1), etc.  Sector-dependent
     normalization.

(R2) The path-tensor V_12 otimes V_13 otimes V_14 has an effective
     COMPACTNESS that scales the U(1) rep labels.  Specifically: a
     full path-tensor rotation is 2pi/(dim V_12 * dim V_13), giving
     smallest charge 1/(dim V_12 * dim V_13).

(R3) Cascade Y is a NORMALIZATION of the J-eigenvalue, not the J-
     eigenvalue itself.  Y = (J-eigenvalue) / (some factor depending
     on sector).

(R4) Cascade U(1)_Y is non-compact (= R, not S^1) at d=14.  Reps
     can have any real charge.  Cascade then needs another mechanism
     to pin specific fractional values.

This script tests each resolution against cascade primitives.

WHAT THIS SCRIPT DELIVERS
=========================
1. Articulates the puzzle precisely.
2. Tests four candidate resolutions.
3. Honest assessment: which (if any) is cascade-native; what's needed
   to close (R1b).
"""

from __future__ import annotations

import math
import sys
from fractions import Fraction


def report_puzzle():
    print("=" * 78)
    print("THE PUZZLE: cascade J at d=14 has integer eigenvalues, SM Y fractional")
    print("=" * 78)
    print()
    print("Cascade U(1)_Y generator: J on R^14 = C^7.")
    print("  J^2 = -I, so J eigenvalues are +/- i.")
    print("  Under exp(theta J), eigenstates pick up phase exp(+/- i theta).")
    print("  In cascade-native units, charges are +/- 1 (integer).")
    print()
    print("Standard rep theory: compact U(1) has integer charges.")
    print("  Smallest non-trivial irrep: charge +/- 1.")
    print("  No fractional charges from compact U(1) action alone.")
    print()
    print("SM Y values:")
    sm_y = {
        "Q_L":  Fraction(1, 6),
        "u_R":  Fraction(2, 3),
        "d_R":  Fraction(-1, 3),
        "L_L":  Fraction(-1, 2),
        "e_R":  Fraction(-1, 1),
        "H":    Fraction(1, 2),
    }
    for name, y in sm_y.items():
        print(f"  Y_{name:5s} = {str(y):>6s}")
    print()
    print("All SM Y values are RATIONAL with denominators in {1, 2, 3, 6}.")
    print("These are FRACTIONS, not the integer charges that J's compactness")
    print("would give.")
    print()
    print("How does the cascade give fractional Y from integer J eigenvalues?")
    print()


def test_R1_sector_dependent_generator():
    print("=" * 78)
    print("CANDIDATE (R1): sector-dependent U(1)_Y generator J/(dim V_12 * dim V_13)")
    print("=" * 78)
    print()
    print("Hypothesis: U(1)_Y on matter in (V_12, V_13) sector is generated")
    print("by J/(dim V_12 * dim V_13), so the smallest non-trivial Y =")
    print("1/(dim V_12 * dim V_13) in cascade-native units.")
    print()
    print("Tests:")
    print()
    sectors = [
        ((3, 2), Fraction(1, 6), "Q_L"),
        ((3, 1), Fraction(1, 3), "u_R, d_R"),
        ((1, 2), Fraction(1, 2), "L_L, H"),
        ((1, 1), Fraction(1, 1), "e_R"),
    ]
    print(f"  {'sector':>10s}  {'1/(dim V_12 * dim V_13)':>24s}  {'matter':>10s}")
    for (v12, v13), unit, matter in sectors:
        print(f"  ({v12}, {v13}){'':>4s}  "
              f"{str(unit):>24s}  {matter:>10s}")
    print()
    print("Cascade-native source for 'sector-dependent generator':")
    print()
    print("  The U(1)_Y action on the path-tensor V_12 otimes V_13 otimes V_14")
    print("  must commute with the SU(3) action on V_12 and SU(2) action on V_13.")
    print()
    print("  For consistency, U(1)_Y action acts on each component with the")
    print("  same phase exp(i Y theta).  This is the STANDARD reading.")
    print()
    print("  But: if we view U(1)_Y as acting on the path-tensor as a single")
    print("  Hilbert space (dim n*m where n = dim V_12, m = dim V_13), the")
    print("  'same phase per component' interpretation gives Y as an integer")
    print("  rep label, NOT 1/(n*m).")
    print()
    print("  PROBLEM: this candidate gets the answer right (1/(n*m) for")
    print("  matter Y) but doesn't EXPLAIN cascade-natively WHY the U(1)_Y")
    print("  generator is sector-dependent.  It's a tautology unless there's")
    print("  a deeper reason.")
    print()
    print("STATUS: assumes the answer; not a derivation.")
    print()


def test_R2_path_tensor_compactness():
    print("=" * 78)
    print("CANDIDATE (R2): path-tensor compactness at 2pi/(dim V_12 * dim V_13)")
    print("=" * 78)
    print()
    print("Hypothesis: the path-tensor V_12 otimes V_13 otimes V_14 has a natural")
    print("ROTATION PERIOD of 2pi/(dim V_12 * dim V_13).  U(1)_Y rotation by")
    print("this small angle returns the path-tensor to itself (modulo SU(3)")
    print("x SU(2) structure).  Smallest matter Y is then this fractional unit.")
    print()
    print("Cascade-native motivation: if U(1)_Y rotation by 2pi/n leaves the")
    print("path-tensor invariant up to a Z_n permutation of components, the")
    print("effective U(1)_Y/Z_n quotient has smallest charge 1/n.")
    print()
    print("Cascade structure that could give Z_n action on path-tensor:")
    print()
    print("  - Z_3 cyclic permutation of color components (Q_L's 3 colors).")
    print("    -> Z_3 invariance of color-sumed states.")
    print()
    print("  - Z_2 isospin flip (Q_L's u <-> d, T_3 reflection).")
    print("    -> Z_2 invariance of doublet sums.")
    print()
    print("  - Combined Z_3 x Z_2 = Z_6 action on (3, 2) sector path-tensor.")
    print("    -> Z_6 invariance of fully-summed states.")
    print()
    print("If U(1)_Y/Z_6 = R/Z is the effective rep group on the (3, 2)-sector")
    print("path-tensor, smallest charge = 1/6.  Sector-fundamental rule!")
    print()
    print("STATUS: cascade-native motivation EXISTS (Z_3 from color + Z_2 from")
    print("isospin = Z_6 on path-tensor).  Closure requires:")
    print()
    print("  (a) Showing that Z_n action genuinely quotients U(1)_Y (not just")
    print("      compatible with it).")
    print("  (b) Showing that the cascade matter content RESPECTS this Z_n")
    print("      quotient (matter states are Z_n-invariant or equivariant).")
    print()
    print("Cascade-native ingredient (a) is plausible: SU(N) has Z_N center,")
    print("which acts trivially on the fundamental rep up to phase.  For SU(3)")
    print("color-triplet Q_L: Z_3 center acts as exp(2 pi i / 3) on each color.")
    print("Combined with Z_2 isospin: Z_6 center acts on (3, 2)-sector states.")
    print()
    print("If U(1)_Y has a Z_n compatible structure with the cascade gauge")
    print("center, U(1)_Y / Z_n quotient gives fractional charges.")
    print()
    print("This is the SAME mechanism as the SM: SU(N) center action + U(1)_Y")
    print("constraint forces fractional Y values via charge quantization.  The")
    print("cascade just inherits this structure cascade-natively.")
    print()


def test_R3_normalization():
    print("=" * 78)
    print("CANDIDATE (R3): Y = J-eigenvalue / (normalization factor)")
    print("=" * 78)
    print()
    print("Hypothesis: cascade Y is NOT the J-eigenvalue but a normalized")
    print("quantity Y = (J-eigenvalue) / N(sector), where N(sector) =")
    print("dim V_12 * dim V_13.")
    print()
    print("Test: J-eigenvalues are +/- 1 (integer).  Y = +/- 1 / N(sector).")
    print()
    print("For (3, 2) sector: N = 6, Y = +/- 1/6.  ✓")
    print("For (3, 1) sector: N = 3, Y = +/- 1/3.  ✓")
    print()
    print("Cascade-native source for the normalization?")
    print()
    print("  - The path-tensor's natural inner product divides phases by N.")
    print("  - Equivalent to viewing Y as 'charge per component' in path-tensor.")
    print("  - If the cascade defines Y via the path-tensor average rather")
    print("    than the J-eigenvalue, fractional values follow.")
    print()
    print("STATUS: this is essentially a re-statement of (R1) with a different")
    print("framing.  Same need: cascade-native reason for the normalization.")
    print()


def test_R4_non_compact_U1():
    print("=" * 78)
    print("CANDIDATE (R4): cascade U(1)_Y is non-compact (R rather than S^1)")
    print("=" * 78)
    print()
    print("Hypothesis: at d=14, the cascade U(1)_Y is generated by J but is")
    print("non-compact (universal cover of S^1 = R).  Reps can have any real")
    print("charge.")
    print()
    print("This would allow fractional Y values trivially -- but doesn't pin")
    print("specific fractions.  Need additional mechanism for 1/6, 1/3, etc.")
    print()
    print("Cascade structure: Adams' theorem at d=14 forces rho(14) - 1 = 1")
    print("nowhere-zero tangent field on S^13.  This gives a U(1) structure.")
    print("J on R^14 = C^7 has integer eigenvalues +/- i, so the U(1) is")
    print("COMPACT (S^1).")
    print()
    print("STATUS: ruled out by cascade structure.  J's integer eigenvalues")
    print("force compact U(1).")
    print()


def report_assessment():
    print("=" * 78)
    print("ASSESSMENT")
    print("=" * 78)
    print()
    print("Of the four candidate mechanisms:")
    print()
    print("  (R1) Sector-dependent generator: tautological without deeper reason.")
    print("  (R2) Path-tensor compactness via Z_n center action: PROMISING.")
    print("       Cascade-native via SU(3)_center = Z_3 + SU(2) flip = Z_2,")
    print("       combined Z_6 on (3, 2)-sector path-tensor.  Closure requires")
    print("       proving that U(1)_Y / Z_n quotient is the effective rep group.")
    print("  (R3) Normalization via path-tensor: re-statement of (R1).")
    print("  (R4) Non-compact U(1)_Y: ruled out by cascade structure.")
    print()
    print("THE PROMISING ANGLE: (R2) -- path-tensor compactness via gauge center")
    print("================================================================")
    print()
    print("The cascade has natural Z_n structure on the path-tensor:")
    print("  - SU(3) center Z_3: acts on V_12 = 3 fundamental as e^{2 pi i / 3}.")
    print("  - SU(2) center Z_2: acts on V_13 = 2 doublet as +/- 1.")
    print("  - Combined Z_3 x Z_2 = Z_6 on (3, 2)-sector path-tensor.")
    print()
    print("If U(1)_Y at d=14 acts on the path-tensor in a way COMPATIBLE with")
    print("this Z_n center action (i.e., U(1)_Y commutes with SU(3)_center")
    print("and SU(2)_center), then the effective rep group on the path-tensor")
    print("is U(1)_Y / Z_n.")
    print()
    print("Compact U(1) / Z_n = S^1 / Z_n, which has reps labeled by Z but")
    print("with smallest non-trivial charge = 1/n in the original U(1) units.")
    print()
    print("For (3, 2) sector: smallest non-trivial Y in cascade-native units =")
    print("1/6.  SECTOR-FUNDAMENTAL RULE EMERGES.")
    print()
    print("WHAT THIS COMMIT EARNS")
    print("=======================")
    print("- Identifies the rep-theoretic mechanism for sector-fundamental")
    print("  rule: U(1)_Y / Z_n quotient via cascade gauge center action.")
    print("- The Z_n structure is cascade-native (SU(3)_center + SU(2)_center).")
    print("- Reduces the (R1b) closure to a specific structural claim:")
    print("  U(1)_Y at d=14 acts on the path-tensor compatibly with the")
    print("  Z_n center action, so the effective rep group is U(1)_Y / Z_n.")
    print()
    print("REMAINING WORK")
    print("==============")
    print("To make this a cascade theorem:")
    print("  (a) Show that U(1)_Y acts compatibly with SU(3)_center x SU(2)_center")
    print("      on the cascade path-tensor.  This is plausible since U(1)_Y")
    print("      commutes with SU(3) and SU(2) by construction (Adams gauge")
    print("      groups at distinct distinguished layers).")
    print("  (b) Show that the cascade matter content RESPECTS the Z_n quotient")
    print("      (matter states are Z_n-equivariant).  This is automatic if")
    print("      matter is in a definite (V_12, V_13) sector (each sector is")
    print("      a definite Z_n-rep).")
    print("  (c) Conclude: the effective U(1)_Y rep group on the (V_12, V_13)-")
    print("      sector path-tensor is U(1)_Y / Z_{dim V_12 * dim V_13}.")
    print("      Smallest charge = 1/(dim V_12 * dim V_13).")
    print()
    print("This is the SAME mechanism as SM charge quantization (Dirac")
    print("quantization on multiply-connected spaces), but cascade-natively")
    print("derived from the cascade gauge groups' centers.")
    print()
    print("STATUS: structurally promising; would require a cascade theorem")
    print("formalizing 'U(1)_Y / (gauge center) is the effective rep group")
    print("on path-tensor' to close (R1b).")
    print()


def main():
    print("=" * 78)
    print("(R1b) attack via representation theory: path-tensor + gauge center")
    print("=" * 78)
    print()
    report_puzzle()
    test_R1_sector_dependent_generator()
    test_R2_path_tensor_compactness()
    test_R3_normalization()
    test_R4_non_compact_U1()
    report_assessment()
    return 0


if __name__ == "__main__":
    sys.exit(main())
