#!/usr/bin/env python3
"""
Research note: are projective U(1) (Part II) and hypercharge U(1) (Part IVa)
the same group, or two distinct U(1)s coexisting in the cascade?

CONTEXT
-------
The cascade now has two U(1) groups derived from cascade structure:

  (P) Projective U(1) (Part II Theorem thm:U1-gauge-forced, Sec 7.5):
      generated by J on the cascade state space R^{2n}, gauges out
      global phase of QM states, makes the projective state space
      CP^{n-1} via Hopf fibration.  Foundational/kinematic.  Forced
      by the cascade hypothesis (under Theorem thm:U1-gauge-forced).

  (Y) Hypercharge U(1) (Part IVa Theorem thm:adams, layer d=14):
      derived from Adams' theorem on S^13: the maximum number of
      linearly independent nowhere-zero tangent vector fields is
      rho(14) - 1 = 1, giving dim U(1) = 1.  Dynamical: this U(1)
      is the gauge group of the hypercharge boson, becomes the
      photon after electroweak symmetry breaking.

These are both abelian, both generated from cascade primitives, both
called "U(1)".  Are they the same group or different?

ABSTRACT vs PHYSICAL IDENTIFICATION
------------------------------------
At the level of abstract Lie groups, U(1) = S^1 is unique up to
isomorphism.  So projective U(1) and hypercharge U(1) are isomorphic
as Lie groups.  This is trivial.

The non-trivial question is whether they are the SAME group as
cascade-internal physical structures -- i.e., whether the projective
U(1)'s action on cascade states is the same as the hypercharge U(1)'s
action on cascade states.  Three distinguishing properties:

  (a) DOMAIN.  Projective U(1) acts on the FULL state space H_R = R^{2n}
      (all cascade content).  Hypercharge U(1) acts on STATES WITH
      NONZERO HYPERCHARGE (a strict subset of the full state space).

  (b) UNIFORMITY.  Projective U(1) acts UNIFORMLY: every state gets
      multiplied by the same phase e^{i*phi}.  Hypercharge U(1) acts
      DIFFERENTIALLY: each state |psi> gets multiplied by e^{i*Y*phi}
      where Y is its hypercharge eigenvalue (an integer or half-integer
      depending on the SM representation).

  (c) OBSERVABILITY.  Projective U(1) is gauge-trivial (Theorem
      thm:U1-gauge-forced): all observables are U(1)-invariant.
      Hypercharge U(1) is observable through gauge interactions: charged
      states couple to the U(1)_Y gauge boson (which becomes the photon
      via electroweak mixing).

Properties (a), (b), (c) are independent and all three hold.  Hence
the two U(1)s are PHYSICALLY DISTINCT, even though abstractly
isomorphic.

CASCADE-INTERNAL DISTINCTION
----------------------------
At the cascade level:

  (P) The projective U(1) is generated by J on the cascade state space.
      J is a structural element of every cascade layer (Part II
      thm:complex: J emerges from forced precession at every step).
      J acts uniformly: all components of any state in H_R = R^{2n}
      are J-rotated by the same phase.

  (Y) The hypercharge U(1) is the unique nonvanishing tangent vector
      field on S^13 (Adams' theorem, Part IVa thm:adams, d=14).  It
      is layer-specific: it lives at d=14, not at every cascade layer.
      Its action on cascade states is via the d=14 gauge layer in the
      cascade descent.

So: the projective U(1) is a GLOBAL structural feature (J at every
layer); the hypercharge U(1) is a LOCAL structural feature (Adams'
field at d=14).  Different cascade-internal origins.

POSSIBLE DEEPER CONNECTION
--------------------------
Despite (a)-(c), there is a structural parallel: both U(1)s arise from
cascade complex/parallelizable structure.  Adams' theorem identifies
S^1, S^3, S^7 as the parallelizable spheres; these correspond to the
Hurwitz division algebras (R, C, H, O) and to the cascade's per-layer
complex structure J.

A speculative reading: the projective U(1) generated by J is
"distributed across all cascade layers"; the hypercharge U(1) at d=14
is the "manifestation of J as a gauge field at the specific layer d=14
where Adams' theorem allows a single nowhere-zero tangent field on
S^{d-1}."  Under this reading, hypercharge is what J becomes when it
acts as a gauge boson at the specific layer where the cascade's
sphere topology supports a 1-dimensional gauge group.

This is a CONJECTURE, not a theorem.  Verifying it would require:

  (i) Showing that the hypercharge generator at d=14 is the
      restriction of the projective J to the d=14 cascade layer.
      Specifically: show that J|_{d=14} acts on the cascade state at
      that layer as the hypercharge generator, with eigenvalues
      matching SM hypercharges.

 (ii) Showing that the gauge coupling g_Y of hypercharge is determined
      by cascade primitives at d=14 (likely related to alpha(14) =
      R(14)^2 / 4, which appears in Theorem thm:alpha-s-closure).

(iii) Explaining why the projective U(1) is "everywhere" but the
      hypercharge U(1) is "only at d=14" -- i.e., why Adams'
      tangent-field obstruction selects out d=14 specifically as the
      layer where J becomes a gauge boson rather than a kinematic
      gauge.

ITEMS (i)-(iii) are open research questions; this script does not
attempt to resolve them.  It records the structural distinction and
the candidate connection.

NUMERICAL ILLUSTRATION
----------------------
The script below illustrates the distinction (a)-(c) numerically by
constructing a toy cascade state with two components carrying
different hypercharges and showing that:
  - Projective U(1) rotation phase-shifts both components by the
    same angle (uniform action).
  - Hypercharge U(1) phase-shifts each component by Y_i * angle
    (differential action).
"""

from __future__ import annotations

import math
import sys

import numpy as np
from scipy.special import gammaln


# ---------------------------------------------------------------------------
# Cascade primitives
# ---------------------------------------------------------------------------

def radon_hurwitz(n: int) -> int:
    """Radon--Hurwitz number rho(n).

    Write n = 2^a * m with m odd; a = 4q + r, 0 <= r <= 3.
    rho(n) = 8q + 2^r.  Adams' theorem: max number of linearly independent
    nowhere-zero tangent vector fields on S^{n-1} is rho(n) - 1.
    """
    if n <= 0:
        raise ValueError("n must be positive")
    a, m = 0, n
    while m % 2 == 0:
        a += 1
        m //= 2
    q, r = divmod(a, 4)
    return 8 * q + 2**r


def R_cascade(d: int) -> float:
    """Cascade radius R(d) = Gamma((d+1)/2) / Gamma((d+2)/2)."""
    return float(np.exp(gammaln((d + 1) / 2.0) - gammaln((d + 2) / 2.0)))


def alpha_cascade(d: int) -> float:
    """Cascade gauge coupling alpha(d) = R(d)^2 / 4 = N(d)^2 / (4 pi)."""
    return R_cascade(d) ** 2 / 4.0


def build_J(n: int) -> np.ndarray:
    """Block-diagonal J on R^{2n}: each 2x2 block is [[0,-1],[1,0]].

    This is the cascade complex structure of Part II thm:complex,
    extended to all n precessing pairs of axes (Part II proof of
    thm:complex: 'Extending to all pairs of precessing axes
    partitions R^{2n} into n complex dimensions C^n').
    """
    J = np.zeros((2 * n, 2 * n))
    for k in range(n):
        J[2 * k, 2 * k + 1] = -1.0
        J[2 * k + 1, 2 * k] = +1.0
    return J


# ---------------------------------------------------------------------------
# Structural analysis: J restricted to the unit sphere
# ---------------------------------------------------------------------------

def structural_analysis(seed: int = 0) -> None:
    """Show that J|_{S^{2n-1}} is a nowhere-zero tangent field, hence
    by Adams' uniqueness on S^{13} it IS the Adams field at d=14."""

    print("-" * 78)
    print("STRUCTURAL ANALYSIS: is hypercharge U(1) just J|_{d=14}?")
    print("-" * 78)
    print()
    print("Claim under test: the hypercharge generator at d=14 is the")
    print("restriction of the global cascade complex structure J to the")
    print("d=14 cascade layer.  Two reductions to check:")
    print()
    print("  (G) Gauge GROUP identity:  exp(theta J) restricted to S^13 is")
    print("      the unique Adams U(1) on S^13 (up to scale).")
    print("  (B) Gauge BOSON action:    J's eigenvalues match SM hypercharges")
    print("      Y in {-1, -1/2, -1/3, +1/6, +2/3, ...}.")
    print()

    # ---- Setup at the d=14 cascade layer --------------------------------
    # d = 14: gauge sphere is S^13 = unit sphere in R^14 = R^{2*7}.
    n = 7
    dim = 2 * n  # = 14
    J = build_J(n)
    rng = np.random.default_rng(seed)

    # Sanity: J^2 = -I  (Part II thm:complex)
    JJ = J @ J
    assert np.allclose(JJ, -np.eye(dim))
    print(f"Cascade J on R^{dim} = R^{{2*{n}}}: built block-diagonal.")
    print(f"  J^2 = -I check:  ||J^2 + I||_F = {np.linalg.norm(JJ + np.eye(dim)):.2e}  OK")
    print()

    # ---- (G1) Tangency: <Jx, x> = 0 -------------------------------------
    print("(G1) TANGENCY.  For every x in S^13, is Jx tangent to the sphere")
    print("     at x?  Tangency at x means <Jx, x> = 0.  Since J is")
    print("     antisymmetric (J^T = -J), <Jx,x> = -<x,Jx> = -<Jx,x>, so")
    print("     <Jx,x> = 0 identically.  Numerical check on 10000 random")
    print("     unit vectors:")
    N_samples = 10000
    X = rng.standard_normal((N_samples, dim))
    X /= np.linalg.norm(X, axis=1, keepdims=True)
    JX = X @ J.T   # Jx for each x as rows
    inner = np.einsum("ij,ij->i", JX, X)
    print(f"     max |<Jx,x>| over {N_samples} samples: {np.max(np.abs(inner)):.2e}  (zero to roundoff)")
    print()

    # ---- (G2) Nowhere-zero: |Jx| = 1 ------------------------------------
    print("(G2) NOWHERE-ZERO.  |Jx|^2 = -<x, J^2 x> = <x,x> = 1, so Jx is")
    print("     a unit tangent vector at every x in S^13.  Numerical check:")
    norms = np.linalg.norm(JX, axis=1)
    print(f"     max ||Jx| - 1| over {N_samples} samples: "
          f"{np.max(np.abs(norms - 1.0)):.2e}  (unit norm to roundoff)")
    print()

    # ---- (G3) Adams' uniqueness at n=14 ---------------------------------
    rho14 = radon_hurwitz(14)
    print(f"(G3) ADAMS' UNIQUENESS AT n=14.  rho(14) = {rho14}, so")
    print(f"     rho(14) - 1 = {rho14 - 1} = max number of linearly independent")
    print( "     nowhere-zero tangent fields on S^13.  Any nowhere-zero")
    print( "     tangent vector field on S^13 spans the unique 1-dimensional")
    print( "     subspace of the (rho(14)-1 = 1)-dimensional Adams parallelism.")
    print( "     By (G1) and (G2), J|_{S^13} is such a field.  Therefore")
    print( "     J|_{S^13} IS the Adams' field on S^13 (up to a constant scalar).")
    print()

    # ---- (G4) The U(1) flow exp(theta J) --------------------------------
    print("(G4) U(1) FLOW.  Since J^2 = -I, exp(theta J) = cos(theta) I +")
    print("     sin(theta) J  (Part II rem:U1-gauge-J: R_phi := cos(phi) I +")
    print("     sin(phi) J).  This is a 1-parameter subgroup of SO(2n),")
    print("     and it preserves S^13 (since exp(theta J) is orthogonal).")
    print("     Numerical check: pick a random x in S^13, evolve, check")
    print("     |x(theta)| = 1 and exp((theta1+theta2) J) = exp(theta1 J)")
    print("     exp(theta2 J) (group law).")
    x0 = X[0]
    thetas = rng.uniform(0, 2 * math.pi, size=20)
    norm_errs = []
    for th in thetas:
        R_th = math.cos(th) * np.eye(dim) + math.sin(th) * J
        x_th = R_th @ x0
        norm_errs.append(abs(np.linalg.norm(x_th) - 1.0))
    th1, th2 = rng.uniform(0, 2 * math.pi, size=2)
    R1 = math.cos(th1) * np.eye(dim) + math.sin(th1) * J
    R2 = math.cos(th2) * np.eye(dim) + math.sin(th2) * J
    R_sum = math.cos(th1 + th2) * np.eye(dim) + math.sin(th1 + th2) * J
    group_err = np.linalg.norm(R1 @ R2 - R_sum)
    print(f"     max |x(theta)| - 1: {max(norm_errs):.2e}")
    print(f"     ||R(t1) R(t2) - R(t1+t2)||_F: {group_err:.2e}")
    print()
    print("     Conclusion (G): the Adams U(1) on S^13 IS the U(1) generated")
    print("     by J|_{S^13}.  This closes the gauge-GROUP identity question.")
    print()

    # ---- (B) Eigenvalue test: does J carry SM hypercharge eigenvalues? --
    print("(B)  GAUGE BOSON ACTION.  In the SM, U(1)_Y acts on a state with")
    print("     hypercharge Y as exp(i Y phi).  For this action to come from")
    print("     J alone, the eigenvalues of J on the cascade state space")
    print("     must match the SM hypercharge spectrum {-1, -1/2, -1/3,")
    print("     +1/6, +2/3, +1, ...}.  Diagonalise J on R^14:")
    eigvals = np.linalg.eigvals(J)
    eigvals_sorted = sorted(eigvals, key=lambda z: (z.imag, z.real))
    distinct = sorted({(round(z.real, 6), round(z.imag, 6)) for z in eigvals_sorted})
    print(f"     spectrum of J on R^{dim}: {len(eigvals_sorted)} eigenvalues")
    print(f"     distinct values (real, imag): {distinct}")
    print(f"     (each appears with multiplicity {dim // len(distinct)})")
    print()
    print("     J has only the eigenvalues +i and -i (each with multiplicity")
    print(f"     n = {n}).  Under exp(theta J), these eigenstates pick up phases")
    print("     +exp(i theta) and exp(-i theta) respectively -- a UNIFORM action,")
    print("     not a Y-graded one.  J alone CANNOT reproduce the SM")
    print("     hypercharge eigenvalues {-1/2, +2/3, ...}.")
    print()
    print("     Conclusion (B): the gauge BOSON's differential action requires")
    print("     a representation structure beyond J -- specifically the")
    print("     Bott-period rep assignments of Part IVa Section 4.  J fixes")
    print("     the GROUP, not the WEIGHTS.")
    print()

    # ---- (C) Coupling test: does alpha(14) match SM g_Y^2/(4 pi)? --------
    a14 = alpha_cascade(14)
    a14_chi = a14 / 2.0  # chi(S^12) = 2 in Part IVb's correction
    g_Y_MZ = 0.357           # SM hypercharge coupling at M_Z, MS-bar
    alpha_Y_MZ = g_Y_MZ ** 2 / (4 * math.pi)
    print("(C)  GAUGE COUPLING.  Cascade coupling at d=14 is alpha(14) =")
    print(f"     R(14)^2 / 4 = {a14:.6f}.  SM hypercharge coupling at M_Z is")
    print(f"     alpha_Y(M_Z) = g_Y^2 / (4 pi) ~ {alpha_Y_MZ:.6f}  "
          f"(g_Y(M_Z) ~ {g_Y_MZ:.3f}).")
    print(f"     Naive ratio alpha(14) / alpha_Y(M_Z) ~ {a14 / alpha_Y_MZ:.3f}  "
          f"(not unity).")
    print(f"     With Part IVb chi=2 quotient: alpha(14)/chi = {a14_chi:.6f},")
    print(f"     ratio to alpha_Y(M_Z): {a14_chi / alpha_Y_MZ:.3f}.")
    print()
    print("     alpha(14) is the cascade-internal coupling at the d=14 layer;")
    print("     it sources Part IVb's universal shift delta Phi_U(1) =")
    print("     alpha(14)/chi (rem:als-closure-structural).  Its relation to")
    print("     g_Y at any particular renormalisation scale is NOT pinned")
    print("     down by the J-restriction argument; this remains open.")
    print()


def main() -> int:
    print("=" * 78)
    print("PROJECTIVE U(1) vs HYPERCHARGE U(1):")
    print("two distinct U(1)s in the cascade, same Lie group abstractly")
    print("=" * 78)
    print()

    # Toy state with two SM-like components: a left-handed lepton (Y = -1/2)
    # and a right-handed up-quark (Y = +2/3).  Hypercharge values are SM.
    # In the cascade, these would both be states in H_R = R^{2n}, but with
    # different hypercharge labels at the d=14 layer.

    # State has two complex components in C^2 = R^4:
    #   psi = (a, b) with a = "lepton amplitude", b = "u-quark amplitude"
    # We pick a generic state and show the two U(1) actions differ.

    psi = np.array([0.6 + 0.3j, 0.5 - 0.4j], dtype=complex)
    psi /= np.linalg.norm(psi)

    Y_lepton = -0.5  # SM hypercharge of left-handed lepton doublet
    Y_uquark = +2.0 / 3.0  # SM hypercharge of right-handed up-quark

    print(f"Toy cascade state:")
    print(f"  psi[0] = {psi[0]:.4f}  (component 'lepton', Y = {Y_lepton:+.3f})")
    print(f"  psi[1] = {psi[1]:.4f}  (component 'u-quark', Y = {Y_uquark:+.3f})")
    print()

    # Pick a phase angle phi
    phi = math.pi / 3  # 60 degrees

    # Projective U(1) action: uniform phase
    psi_proj = np.exp(1j * phi) * psi

    # Hypercharge U(1) action: differential phase per component
    psi_hyper = np.array([
        np.exp(1j * Y_lepton * phi) * psi[0],
        np.exp(1j * Y_uquark * phi) * psi[1],
    ])

    print(f"Apply U(1) rotation with phi = pi/3 = {phi:.4f}:")
    print()
    print(f"  Projective U(1) (uniform e^(i*phi)):")
    print(f"    psi_proj[0] = {psi_proj[0]:.4f}")
    print(f"    psi_proj[1] = {psi_proj[1]:.4f}")
    print(f"    Born |psi_proj|^2 = ({abs(psi_proj[0])**2:.4f}, "
          f"{abs(psi_proj[1])**2:.4f})  (unchanged)")
    print()
    print(f"  Hypercharge U(1) (e^(i*Y*phi) per component):")
    print(f"    psi_hyper[0] = {psi_hyper[0]:.4f}")
    print(f"    psi_hyper[1] = {psi_hyper[1]:.4f}")
    print(f"    Born |psi_hyper|^2 = ({abs(psi_hyper[0])**2:.4f}, "
          f"{abs(psi_hyper[1])**2:.4f})  (unchanged within components)")
    print()

    # The key distinguishing observable is the relative phase between components
    # (interference term).  This is observable in interference experiments.
    rel_phase_orig = np.angle(psi[1] / psi[0])
    rel_phase_proj = np.angle(psi_proj[1] / psi_proj[0])
    rel_phase_hyper = np.angle(psi_hyper[1] / psi_hyper[0])

    print(f"Relative phase psi[1]/psi[0] (observable in interference):")
    print(f"  Original:    {rel_phase_orig:+.4f} rad")
    print(f"  After proj:  {rel_phase_proj:+.4f} rad  "
          f"(unchanged: uniform U(1) preserves relative phase)")
    print(f"  After hyper: {rel_phase_hyper:+.4f} rad  "
          f"(SHIFTED by (Y_2 - Y_1) * phi = "
          f"{(Y_uquark - Y_lepton) * phi:+.4f})")
    print()

    proj_change = abs(rel_phase_proj - rel_phase_orig)
    hyper_change = abs(rel_phase_hyper - rel_phase_orig)

    print(f"Relative-phase change:")
    print(f"  Projective U(1):  {proj_change:.6e}  (zero -> NOT observable)")
    print(f"  Hypercharge U(1): {hyper_change:.6f}  (nonzero -> observable)")
    print()

    structural_analysis()

    print("-" * 78)
    print("CONCLUSION (NARROWED, 2026-04)")
    print("-" * 78)
    print()
    print("The original conjecture had three sub-claims (i)/(ii)/(iii).  The")
    print("structural analysis above settles them as follows.")
    print()
    print("  (i)  GAUGE GROUP IDENTITY  -- CLOSED structurally.")
    print("       J on R^{2n} is antisymmetric and squares to -I, so J|_{S^{2n-1}}")
    print("       is automatically a unit-norm tangent vector field at every")
    print("       point.  At n=7 (the d=14 cascade layer), Adams' theorem says")
    print("       there is a UNIQUE such field on S^13 up to scale (rho(14)-1=1).")
    print("       Therefore the Adams' field on S^13 IS the restriction of the")
    print("       global cascade J to S^13.  The hypercharge gauge GROUP")
    print("       exp(theta J|_{S^13}) and the projective U(1) exp(theta J)")
    print("       are generated by the same J -- one globally, one restricted.")
    print()
    print("  (ii) GAUGE BOSON DIFFERENTIAL ACTION  -- FALSIFIED (for J alone).")
    print("       J's eigenvalues on R^{2n} are exactly +/- i, each with")
    print("       multiplicity n.  Under exp(theta J) every eigenstate picks")
    print("       up phase exp(+/- i theta) -- a UNIFORM action, not the")
    print("       Y-graded action exp(i Y phi) with Y in {-1/2, -1/3, +1/6,")
    print("       +2/3, ...}.  J alone cannot reproduce SM hypercharge weights.")
    print("       The Y-grading must come from a separate ingredient -- Part")
    print("       IVa Section 4's Bott-period representation assignments --")
    print("       not from J.  The strong reading of the conjecture (J carries")
    print("       SM hypercharge eigenvalues directly) is wrong.")
    print()
    print(" (iii) WHY d=14 SPECIFICALLY  -- PARTIALLY EXPLAINED.")
    print("       J|_{S^{2n-1}} is a nowhere-zero tangent field at every n,")
    print("       so the Adams criterion does not by itself single out n=7.")
    print("       What singles out n=7 (i.e. d=14) is that 1 = rho(14)-1 is")
    print("       the EXACT count of independent fields, so the U(1)")
    print("       generated by J|_{S^13} fills the entire Adams parallelism.")
    print("       At n=4 (d=8) the parallelism has dimension 7 (octonionic),")
    print("       so a single J-flow leaves 6 independent directions un-gauged;")
    print("       Adams' non-Lie-group obstruction (S^7 not an H-space) then")
    print("       blocks the gauge-group reading.  At n=2 (d=4), rho(4)-1=3")
    print("       gives the spacetime spatial directions (Bott mirror), not")
    print("       a gauge layer.  d=14 is the unique layer in [5, d_1=19]")
    print("       where the Adams parallelism is 1-dimensional and the")
    print("       J-restriction fills it -- a structural coincidence between")
    print("       Bott periodicity and forced precession.")
    print()
    print("OPEN ITEMS (smaller than before)")
    print()
    print("  (Y-grading)  Derive the SM hypercharge spectrum from Part IVa")
    print("    Section 4's Bott-period representation structure, not from J.")
    print("    Confirm this is what the existing `tools/verifiers/` machinery")
    print("    already encodes; if so, the open question reduces to a")
    print("    citation/exposition issue, not a derivation gap.")
    print()
    print("  (g_Y vs alpha(14))  alpha(14) = R(14)^2/4 is the cascade")
    print("    coupling at the d=14 layer (used in Part IVb's universal")
    print("    delta Phi_U(1) = alpha(14)/chi shift).  Its relation to the")
    print("    SM running coupling g_Y at any particular renormalisation")
    print("    scale is not closed by the J-restriction argument and remains")
    print("    a separate open question.")
    print()
    print("DOCUMENTATION IMPACT")
    print()
    print("Part IVa rem:u1-vs-projective's 'speculative connection' paragraph")
    print("can be tightened: the gauge-group identity is now structurally")
    print("closed (J|_{S^13} = Adams' field by uniqueness), but the conjecture")
    print("that J reproduces SM hypercharge eigenvalues is falsified (J has")
    print("only +/- i eigenvalues).  The two U(1)s are 'the same J seen")
    print("globally vs. restricted to the d=14 sphere'; the differential")
    print("Y-graded action requires Part IVa Section 4's rep structure as")
    print("a separate ingredient.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
