#!/usr/bin/env python3
"""
Research note: are projective U(1) (Part II) and hypercharge U(1) (Part IVa)
the same group, or two distinct U(1)s coexisting in the cascade?

CONTEXT
-------
The cascade now has two U(1) groups derived from cascade structure:

  (P) Projective U(1) (Part II Theorem thm:U1-gauge-forced, Sec 7.4):
      generated by J on the cascade state space R^{2n}, gauges out
      global phase of QM states, makes the projective state space
      CP^{n-1} via Hopf fibration.  Foundational/kinematic.  Forced
      by the cascade hypothesis (under Theorem thm:U1-gauge-forced).

  (Y) Hypercharge U(1) (Part IVa Theorem thm:adams, layer d=14):
      derived from Adams' theorem on S^13: the maximum number of
      linearly independent nowhere-zero tangent vector fields is
      rho(14) - 1 = 1, giving dim U(1) = 1.  Dynamical: this U(1)
      is the gauge group of the hypercharge boson, becomes the
      photon after electroweak symmetry breaking.

These are both abelian, both generated from cascade primitives, both
called "U(1)".  Are they the same group or different?

ABSTRACT vs PHYSICAL IDENTIFICATION
------------------------------------
At the level of abstract Lie groups, U(1) = S^1 is unique up to
isomorphism.  So projective U(1) and hypercharge U(1) are isomorphic
as Lie groups.  This is trivial.

The non-trivial question is whether they are the SAME group as
cascade-internal physical structures -- i.e., whether the projective
U(1)'s action on cascade states is the same as the hypercharge U(1)'s
action on cascade states.  Three distinguishing properties:

  (a) DOMAIN.  Projective U(1) acts on the FULL state space H_R = R^{2n}
      (all cascade content).  Hypercharge U(1) acts on STATES WITH
      NONZERO HYPERCHARGE (a strict subset of the full state space).

  (b) UNIFORMITY.  Projective U(1) acts UNIFORMLY: every state gets
      multiplied by the same phase e^{i*phi}.  Hypercharge U(1) acts
      DIFFERENTIALLY: each state |psi> gets multiplied by e^{i*Y*phi}
      where Y is its hypercharge eigenvalue (an integer or half-integer
      depending on the SM representation).

  (c) OBSERVABILITY.  Projective U(1) is gauge-trivial (Theorem
      thm:U1-gauge-forced): all observables are U(1)-invariant.
      Hypercharge U(1) is observable through gauge interactions: charged
      states couple to the U(1)_Y gauge boson (which becomes the photon
      via electroweak mixing).

Properties (a), (b), (c) are independent and all three hold.  Hence
the two U(1)s are PHYSICALLY DISTINCT, even though abstractly
isomorphic.

CASCADE-INTERNAL DISTINCTION
----------------------------
At the cascade level:

  (P) The projective U(1) is generated by J on the cascade state space.
      J is a structural element of every cascade layer (Part II
      thm:complex: J emerges from forced precession at every step).
      J acts uniformly: all components of any state in H_R = R^{2n}
      are J-rotated by the same phase.

  (Y) The hypercharge U(1) is the unique nonvanishing tangent vector
      field on S^13 (Adams' theorem, Part IVa thm:adams, d=14).  It
      is layer-specific: it lives at d=14, not at every cascade layer.
      Its action on cascade states is via the d=14 gauge layer in the
      cascade descent.

So: the projective U(1) is a GLOBAL structural feature (J at every
layer); the hypercharge U(1) is a LOCAL structural feature (Adams'
field at d=14).  Different cascade-internal origins.

POSSIBLE DEEPER CONNECTION
--------------------------
Despite (a)-(c), there is a structural parallel: both U(1)s arise from
cascade complex/parallelizable structure.  Adams' theorem identifies
S^1, S^3, S^7 as the parallelizable spheres; these correspond to the
Hurwitz division algebras (R, C, H, O) and to the cascade's per-layer
complex structure J.

A speculative reading: the projective U(1) generated by J is
"distributed across all cascade layers"; the hypercharge U(1) at d=14
is the "manifestation of J as a gauge field at the specific layer d=14
where Adams' theorem allows a single nowhere-zero tangent field on
S^{d-1}."  Under this reading, hypercharge is what J becomes when it
acts as a gauge boson at the specific layer where the cascade's
sphere topology supports a 1-dimensional gauge group.

This is a CONJECTURE, not a theorem.  Verifying it would require:

  (i) Showing that the hypercharge generator at d=14 is the
      restriction of the projective J to the d=14 cascade layer.
      Specifically: show that J|_{d=14} acts on the cascade state at
      that layer as the hypercharge generator, with eigenvalues
      matching SM hypercharges.

 (ii) Showing that the gauge coupling g_Y of hypercharge is determined
      by cascade primitives at d=14 (likely related to alpha(14) =
      R(14)^2 / 4, which appears in Theorem thm:alpha-s-closure).

(iii) Explaining why the projective U(1) is "everywhere" but the
      hypercharge U(1) is "only at d=14" -- i.e., why Adams'
      tangent-field obstruction selects out d=14 specifically as the
      layer where J becomes a gauge boson rather than a kinematic
      gauge.

ITEMS (i)-(iii) are open research questions; this script does not
attempt to resolve them.  It records the structural distinction and
the candidate connection.

NUMERICAL ILLUSTRATION
----------------------
The script below illustrates the distinction (a)-(c) numerically by
constructing a toy cascade state with two components carrying
different hypercharges and showing that:
  - Projective U(1) rotation phase-shifts both components by the
    same angle (uniform action).
  - Hypercharge U(1) phase-shifts each component by Y_i * angle
    (differential action).
"""

from __future__ import annotations

import math
import sys

import numpy as np


def main() -> int:
    print("=" * 78)
    print("PROJECTIVE U(1) vs HYPERCHARGE U(1):")
    print("two distinct U(1)s in the cascade, same Lie group abstractly")
    print("=" * 78)
    print()

    # Toy state with two SM-like components: a left-handed lepton (Y = -1/2)
    # and a right-handed up-quark (Y = +2/3).  Hypercharge values are SM.
    # In the cascade, these would both be states in H_R = R^{2n}, but with
    # different hypercharge labels at the d=14 layer.

    # State has two complex components in C^2 = R^4:
    #   psi = (a, b) with a = "lepton amplitude", b = "u-quark amplitude"
    # We pick a generic state and show the two U(1) actions differ.

    psi = np.array([0.6 + 0.3j, 0.5 - 0.4j], dtype=complex)
    psi /= np.linalg.norm(psi)

    Y_lepton = -0.5  # SM hypercharge of left-handed lepton doublet
    Y_uquark = +2.0 / 3.0  # SM hypercharge of right-handed up-quark

    print(f"Toy cascade state:")
    print(f"  psi[0] = {psi[0]:.4f}  (component 'lepton', Y = {Y_lepton:+.3f})")
    print(f"  psi[1] = {psi[1]:.4f}  (component 'u-quark', Y = {Y_uquark:+.3f})")
    print()

    # Pick a phase angle phi
    phi = math.pi / 3  # 60 degrees

    # Projective U(1) action: uniform phase
    psi_proj = np.exp(1j * phi) * psi

    # Hypercharge U(1) action: differential phase per component
    psi_hyper = np.array([
        np.exp(1j * Y_lepton * phi) * psi[0],
        np.exp(1j * Y_uquark * phi) * psi[1],
    ])

    print(f"Apply U(1) rotation with phi = pi/3 = {phi:.4f}:")
    print()
    print(f"  Projective U(1) (uniform e^(i*phi)):")
    print(f"    psi_proj[0] = {psi_proj[0]:.4f}")
    print(f"    psi_proj[1] = {psi_proj[1]:.4f}")
    print(f"    Born |psi_proj|^2 = ({abs(psi_proj[0])**2:.4f}, "
          f"{abs(psi_proj[1])**2:.4f})  (unchanged)")
    print()
    print(f"  Hypercharge U(1) (e^(i*Y*phi) per component):")
    print(f"    psi_hyper[0] = {psi_hyper[0]:.4f}")
    print(f"    psi_hyper[1] = {psi_hyper[1]:.4f}")
    print(f"    Born |psi_hyper|^2 = ({abs(psi_hyper[0])**2:.4f}, "
          f"{abs(psi_hyper[1])**2:.4f})  (unchanged within components)")
    print()

    # The key distinguishing observable is the relative phase between components
    # (interference term).  This is observable in interference experiments.
    rel_phase_orig = np.angle(psi[1] / psi[0])
    rel_phase_proj = np.angle(psi_proj[1] / psi_proj[0])
    rel_phase_hyper = np.angle(psi_hyper[1] / psi_hyper[0])

    print(f"Relative phase psi[1]/psi[0] (observable in interference):")
    print(f"  Original:    {rel_phase_orig:+.4f} rad")
    print(f"  After proj:  {rel_phase_proj:+.4f} rad  "
          f"(unchanged: uniform U(1) preserves relative phase)")
    print(f"  After hyper: {rel_phase_hyper:+.4f} rad  "
          f"(SHIFTED by (Y_2 - Y_1) * phi = "
          f"{(Y_uquark - Y_lepton) * phi:+.4f})")
    print()

    proj_change = abs(rel_phase_proj - rel_phase_orig)
    hyper_change = abs(rel_phase_hyper - rel_phase_orig)

    print(f"Relative-phase change:")
    print(f"  Projective U(1):  {proj_change:.6e}  (zero -> NOT observable)")
    print(f"  Hypercharge U(1): {hyper_change:.6f}  (nonzero -> observable)")
    print()

    print("-" * 78)
    print("CONCLUSION")
    print("-" * 78)
    print()
    print("Projective U(1) and hypercharge U(1) are PHYSICALLY DISTINCT in the")
    print("cascade, even though abstractly both are U(1) = S^1:")
    print()
    print("  - Projective U(1) acts UNIFORMLY (same phase for all components).")
    print("    Its action is GAUGE-TRIVIAL: relative phases are preserved,")
    print("    so no observable consequence.  This is the QM phase gauge.")
    print()
    print("  - Hypercharge U(1) acts DIFFERENTIALLY (phase = Y * phi).")
    print("    Its action SHIFTS RELATIVE PHASES: observable in interference,")
    print("    couples to gauge bosons (becomes photon after EW breaking).")
    print()
    print("Cascade-internal origins are also distinct:")
    print("  - Projective U(1) = exp(J*phi), with J the global cascade complex")
    print("    structure (Part II thm:complex).  Lives at EVERY cascade layer.")
    print("  - Hypercharge U(1) = the unique Adams' tangent field on S^13")
    print("    (Part IVa thm:adams).  Lives at the SPECIFIC layer d=14.")
    print()
    print("OPEN STRUCTURAL QUESTION (conjecture, not a theorem):")
    print("  Is the hypercharge generator at d=14 the restriction of the global")
    print("  projective J to the d=14 cascade layer?  If so, hypercharge would")
    print("  be 'J becoming a gauge field at the specific layer where Adams'")
    print("  obstruction allows a 1-dim gauge group on the per-layer sphere.'")
    print()
    print("  Verifying this would require:")
    print("    (i) Showing J|_{d=14} acts as the hypercharge generator with")
    print("        eigenvalues matching SM hypercharges.")
    print("   (ii) Deriving the hypercharge coupling g_Y from cascade primitives")
    print("        at d=14 (likely related to alpha(14) = R(14)^2 / 4).")
    print("  (iii) Explaining why d=14 specifically -- why Adams' theorem at")
    print("        d=14 selects this layer as the one where J manifests as a")
    print("        gauge boson rather than a kinematic gauge.")
    print()
    print("These open questions are flagged for further development; not")
    print("resolved by this script.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
