"""CERTIFIED NEGATIVE DIRECTIONS OF THE SEMI-LOCAL TILES (owner: "Prove it";
Addendum 424). A research witness -- not a tower member, not cited by the paper.
The ENCLOSURE is rigorous (the committed Temple machinery); the trial is data.
For a tile S and an odd support length delta past its window, build the
float64 pure-harmonic ground state of the S-local t-space operator (a frozen
trial; no rigor burden), then enclose its Rayleigh quotient rho = M/n on the
INTERVAL S-local operator with the committed Temple machinery.  If the
enclosure's upper end is < 0, the S-local form has a certified negative
direction at that delta: a computer-assisted theorem that the tile fails.
  mode 'one'  : S = {inf, 2}, the committed one-prime interval operator
                (oneprime_interval_temple.ClosedT), delta just past log 3.
  mode 'arch' : S = {inf}, the prime-free variant generated from the
                one-prime instrument by exact substitution (the C2 shift
                multiplied by the exact zero interval), delta past log 2.
Usage: certify_negative.py <one|arch> <delta> [ht] [htab]
"""
import sys, os, math, time, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
SP = os.path.join(HERE, 'checkpoints')
import numpy as np

mode, delta = sys.argv[1], float(sys.argv[2])
ht = float(sys.argv[3]) if len(sys.argv) > 3 else 1e-4
htab = float(sys.argv[4]) if len(sys.argv) > 4 else 5e-5
a = delta/2
primes = (2,) if mode == "one" else ()

# ---- the frozen trial: pure odd harmonics, the S-local float ground state
import oneprime_fractional as opf
import twoprime_recon as TR
from scipy.linalg import eigh as scipy_eigh
md = opf.Modes(a, "odd", nus=(), nfr=0, nrough=0)
tn, tw, B, TB, _v = TR.apply_T(md, primes, base=0.003)
N = 2*(B*tw[None, :]) @ B.T; M = 2*(B*tw[None, :]) @ TB.T
N, M = (N + N.T)/2, (M + M.T)/2
# the harmonic set is nearly dependent: whiten (the fixture builder's cut), solve, map back
d = 1.0/np.sqrt(np.diag(N))
ev, U = np.linalg.eigh(d[:, None]*N*d[None, :])
keep = ev > 1e-4
Wh = ((U[:, keep]/np.sqrt(ev[keep])[None, :]).T*d[None, :])
NA = Wh @ N @ Wh.T; MA = Wh @ M @ Wh.T
NA, MA = (NA + NA.T)/2, (MA + MA.T)/2
lam, vec = scipy_eigh(MA, NA)
c = np.array(Wh.T @ vec[:, 0]); c = c/math.sqrt(float(c @ N @ c))
rho_float = float(c @ M @ c)
print(f"[{mode}] delta {delta}: float harmonic ground state rho = {rho_float:+.6e} (lambda_2 {lam[1]:+.3e}), nharm {md.nharm}", flush=True)
fx = {"a": a, "parity": "odd", "nustar": 0.01, "delta": delta, "c": list(map(float, c)),
      "rho_float": rho_float, "ws": list(map(float, md.w)), "nharm": int(md.nharm)}

# ---- the interval operator
if mode == "one":
    import oneprime_interval_temple as T
    temple_cell = T.temple_cell
else:
    src = open(os.path.join(HERE, 'oneprime_interval_temple.py')).read()
    subs = [("        prime = V.scalar(C2I*I(0.5), n)*(p1 + p2)", "        prime = V.scalar(I(0.0), n)*(p1 + p2)"),
            ("        dprime = V.scalar(C2I*I(0.5), n)*(dp1 + dp2)", "        dprime = V.scalar(I(0.0), n)*(dp1 + dp2)"),
            ("        prime = C2I*I(0.5)*(p1 + p2)", "        prime = I(0.0)*(p1 + p2)"),
            ("        dprime = C2I*I(0.5)*(dp1 + dp2)", "        dprime = I(0.0)*(dp1 + dp2)")]
    for old, new in subs:
        assert src.count(old) == 1, old
        src = src.replace(old, new)
    src = src.split("\ndef run(")[0]          # drop the runner and main
    import types
    T = types.ModuleType("arch_witness_temple")
    T.__file__ = os.path.join(HERE, "oneprime_interval_temple.py")   # HERE resolves to the research directory
    exec(compile(src, T.__file__, "exec"), T.__dict__)             # the generated operator lives in memory only
    temple_cell = T.temple_cell
    print("[arch] prime-free interval operator generated by 4 exact substitutions", flush=True)

t0 = time.time()
tr = T.trial_from_fixture(fx, fx["c"])
tabs = T.build_tables(a, [(tr.ws[i], tr.wI(i)) for i in range(len(tr.ws))], tr.deg, htab)
print(f"  tables built {time.time()-t0:.0f}s", flush=True)
res = temple_cell(tr, tabs, T.I(fx["nustar"]), True, ht=ht, theta=0.02)
lo, hi = res["rho"]
print(f"  INTERVAL rho in [{lo:+.6e}, {hi:+.6e}] (width {hi-lo:.2e}); n in {res['n']}; {time.time()-t0:.0f}s", flush=True)
verdict = "CERTIFIED NEGATIVE DIRECTION" if hi < 0 else ("indefinite enclosure" if lo < 0 else "positive on this trial")
print(f"  {mode} delta {delta}: {verdict}", flush=True)
json.dump({"mode": mode, "delta": delta, "ht": ht, "htab": htab, "rho_float": rho_float, "rho": [lo, hi],
           "n": res["n"], "ncells": res["ncells"], "verdict": verdict, "fixture": fx},
          open(os.path.join(SP, f"tile_failure_{mode}_{delta}.json"), "w"), indent=1)
