#!/usr/bin/env python3
"""
Generate the DESI DR2 BAO comparison table as a LaTeX fragment.
Run before LaTeX compilation; output is \input{}'d by Part V.

Cascade parameters are functions of pi alone (plus M_Pl,red).
"""

import os
import sys

import numpy as np
from scipy import integrate

# Shared cascade primitives.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from cascade_constants import (  # noqa: E402
    H0, Omega_m, Omega_m_bott, Omega_b, Omega_r, Omega_Lambda,
    N_eff, c_km_s, pi,
)

h = H0 / 100.0
Omega_m_leading = Omega_m          # leading order = 1/pi

factor_nu = 1.0 + (7.0 / 8.0) * (4.0 / 11.0) ** (4.0 / 3.0) * N_eff

# === Planck parameters ===
H0_planck = 67.4
Omega_m_planck = 0.315
Omega_b_planck = 0.0493
Omega_r_planck = 9.15e-5
Omega_Lambda_planck = 1.0 - Omega_m_planck - Omega_r_planck
r_d_planck = 147.60

# === DESI DR2 data ===
desi_data = [
    (0.295, "D_V",  7.930, 0.150),
    (0.510, "D_M", 13.650, 0.200),
    (0.510, "D_H", 20.890, 0.490),
    (0.706, "D_M", 16.970, 0.240),
    (0.706, "D_H", 20.270, 0.470),
    (0.934, "D_M", 21.790, 0.240),
    (0.934, "D_H", 17.730, 0.300),
    (1.321, "D_M", 27.680, 0.500),
    (1.321, "D_H", 13.850, 0.340),
    (1.484, "D_M", 30.420, 0.660),
    (1.484, "D_H", 13.240, 0.450),
    (2.330, "D_M", 39.200, 0.560),
    (2.330, "D_H",  8.540, 0.140),
]


def make_cosmology(H0_val, Omega_m_val, Omega_r_val, Omega_Lambda_val,
                   Omega_b_val):
    """Return distance functions and r_d for a given parameter set."""
    h_val = H0_val / 100.0
    omega_m = Omega_m_val * h_val**2
    omega_b = Omega_b_val * h_val**2
    Omega_gamma = Omega_r_val / factor_nu
    omega_gamma = Omega_gamma * h_val**2

    def H(z):
        return H0_val * np.sqrt(
            Omega_r_val * (1 + z)**4
            + Omega_m_val * (1 + z)**3
            + Omega_Lambda_val
        )

    def D_M(z):
        result, _ = integrate.quad(lambda zp: c_km_s / H(zp), 0, z)
        return result

    def D_H(z):
        return c_km_s / H(z)

    def D_V(z):
        dm = D_M(z)
        dh = D_H(z)
        return (z * dh * dm**2) ** (1.0 / 3.0)

    # E&H98 fitting formula for r_d
    r_d = 147.60 * (omega_m / 0.1432)**(-0.255) * (omega_b / 0.02237)**(-0.127)

    return D_M, D_H, D_V, r_d


def compute_table(D_M, D_H, D_V, r_d):
    """Compute predictions and pulls for DESI data."""
    results = []
    chi2 = 0.0
    for z, typ, obs, sig in desi_data:
        if typ == "D_V":
            pred = D_V(z) / r_d
        elif typ == "D_M":
            pred = D_M(z) / r_d
        elif typ == "D_H":
            pred = D_H(z) / r_d
        pull = (pred - obs) / sig
        chi2 += pull**2
        results.append((z, typ, obs, sig, pred, pull))
    return results, chi2


# === Compute all three models ===
# Cascade (updated, leading Omega_m = 1/pi)
DM_c, DH_c, DV_c, rd_c = make_cosmology(
    H0, Omega_m_leading, Omega_r, Omega_Lambda, Omega_b)
res_cascade, chi2_cascade = compute_table(DM_c, DH_c, DV_c, rd_c)

# Cascade (Bott Omega_m)
DM_b, DH_b, DV_b, rd_b = make_cosmology(
    H0, Omega_m_bott, Omega_r, 1.0 - Omega_m_bott - Omega_r, Omega_b)
res_bott, chi2_bott = compute_table(DM_b, DH_b, DV_b, rd_b)

# Planck
DM_p, DH_p, DV_p, _ = make_cosmology(
    H0_planck, Omega_m_planck, Omega_r_planck, Omega_Lambda_planck,
    Omega_b_planck)
res_planck, chi2_planck = compute_table(DM_p, DH_p, DV_p, r_d_planck)

# Acoustic scale
DM_star_c = DM_c(1089.0)
ell_A_cascade = pi * DM_star_c / rd_c

n = len(desi_data)

# === Write LaTeX fragment ===
out_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'src', 'generated')
os.makedirs(out_dir, exist_ok=True)

# --- BAO comparison table ---
with open(os.path.join(out_dir, 'bao-table.tex'), 'w') as f:
    f.write('%% Auto-generated by tools/generators/generate_bao_table.py\n')
    f.write('%% Cascade: H0=%.2f, Omega_m=1/pi=%.5f, r_d=%.1f Mpc\n'
            % (H0, Omega_m_leading, rd_c))
    f.write('%% Bott:    H0=%.2f, Omega_m=%.5f, r_d=%.1f Mpc\n'
            % (H0, Omega_m_bott, rd_b))
    f.write('%% Planck:  H0=%.1f, Omega_m=%.3f, r_d=%.1f Mpc\n'
            % (H0_planck, Omega_m_planck, r_d_planck))
    f.write('\\begin{center}\n')
    f.write('\\small\n')
    f.write('\\begin{tabular}{llccccrr}\n')
    f.write('\\hline\n')
    f.write('$z_{\\rm eff}$ & Type & DESI DR2 & $\\sigma$ '
            '& Cascade & Bott & Pull$_{\\rm cas}$ '
            '& Pull$_{\\rm Planck}$ \\\\\n')
    f.write('\\hline\n')
    for i in range(n):
        z, typ, obs, sig, pred_c, pull_c = res_cascade[i]
        _, _, _, _, pred_b, pull_b = res_bott[i]
        _, _, _, _, pred_p, pull_p = res_planck[i]
        typ_tex = '$%s/r_d$' % typ
        dagger = '$^\\dagger$' if (z == 0.510 and typ == "D_H") else ''
        f.write('%.3f%s & %s & %.3f & %.3f & %.3f & %.3f '
                '& $%+.2f\\sigma$ & $%+.2f\\sigma$ \\\\\n'
                % (z, dagger, typ_tex, obs, sig, pred_c, pred_b,
                   pull_c, pull_p))
    f.write('\\hline\n')
    f.write('\\multicolumn{4}{l}{$\\chi^2$ total} '
            '& %.2f & %.2f & '
            '& %.2f \\\\\n' % (chi2_cascade, chi2_bott, chi2_planck))
    f.write('\\multicolumn{4}{l}{$\\chi^2/n$ ($n = %d$)} '
            '& %.3f & %.3f & '
            '& %.3f \\\\\n' % (n, chi2_cascade / n, chi2_bott / n,
                               chi2_planck / n))
    f.write('\\hline\n')
    f.write('\\end{tabular}\n')
    f.write('\\end{center}\n')
    f.write('\\noindent$^\\dagger$: The $z = 0.510$, $D_H/r_d$ bin is '
            'a shared outlier; see Remark~\\ref{rem:outlier}.\n')

# --- Summary values for use in text ---
with open(os.path.join(out_dir, 'bao-values.tex'), 'w') as f:
    f.write('%% Auto-generated by tools/generators/generate_bao_table.py\n')
    f.write('\\newcommand{\\cascadeRd}{%.1f}\n' % rd_c)
    f.write('\\newcommand{\\bottRd}{%.1f}\n' % rd_b)
    f.write('\\newcommand{\\planckRd}{%.1f}\n' % r_d_planck)
    f.write('\\newcommand{\\cascadeChiSq}{%.2f}\n' % chi2_cascade)
    f.write('\\newcommand{\\bottChiSq}{%.2f}\n' % chi2_bott)
    f.write('\\newcommand{\\planckChiSq}{%.2f}\n' % chi2_planck)
    f.write('\\newcommand{\\cascadeChiSqN}{%.3f}\n' % (chi2_cascade / n))
    f.write('\\newcommand{\\bottChiSqN}{%.3f}\n' % (chi2_bott / n))
    f.write('\\newcommand{\\planckChiSqN}{%.3f}\n' % (chi2_planck / n))
    f.write('\\newcommand{\\cascadeEllA}{%.1f}\n' % ell_A_cascade)

# Print summary to stdout for CI logs
print("BAO table generated successfully.")
print(f"  Cascade (1/pi):  r_d = {rd_c:.1f} Mpc, chi2/n = {chi2_cascade/n:.3f}")
print(f"  Cascade (Bott):  r_d = {rd_b:.1f} Mpc, chi2/n = {chi2_bott/n:.3f}")
print(f"  Planck LCDM:     r_d = {r_d_planck:.1f} Mpc, chi2/n = {chi2_planck/n:.3f}")
print(f"  ell_A (cascade): {ell_A_cascade:.1f}")
